FROM python:3.10 as base
USER root

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN apt-get update && apt-get install -y libxml2 g++ vim coreutils nano git libxrender1 wget fakeroot tzdata locales && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN ln -fs /usr/share/zoneinfo/Europe/Prague /etc/localtime && dpkg-reconfigure --frontend noninteractive tzdata && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && locale-gen

RUN pip install --upgrade pip

COPY . /scripts
WORKDIR /scripts

RUN mkdir /.cache
RUN chmod 777 -R /.cache
COPY --chown=root:root / /


RUN pip install torch==2.1.1
RUN pip install torch-scatter torch-cluster -f https://pytorch-geometric.com/whl/torch-2.1.1+cu121.html
RUN pip install torchdrug pandas pyyaml biopython 

ENV TZ Europe/Prague
ENV PATH /opt/conda/bin:/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin